In [ ]:
## Exercise 1: Create two dimensional 3*3 array and perform ndim, shape, slicing operation on it.

In [1]:
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print("Number of dimensions (ndim):", arr.ndim)
print("Shape of array:", arr.shape)
print("First row:", arr[0])             
print("Second column:", arr[:, 1])      
print("Element at (2, 2):", arr[2, 2])  
print("Subarray (first 2 rows, first 2 columns):\n", arr[:2, :2])

Number of dimensions (ndim): 2
Shape of array: (3, 3)
First row: [1 2 3]
Second column: [2 5 8]
Element at (2, 2): 9
Subarray (first 2 rows, first 2 columns):
 [[1 2]
 [4 5]]


In [ ]:
## Exercise 2: Create one dimensional array and perform ndim, shape, reshape operation on it.

In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
print("Number of dimensions (ndim):", arr.ndim)
print("Shape of array:", arr.shape)
reshaped_arr = arr.reshape(2, 3)
print("Reshaped array (2x3):\n", reshaped_arr)

Number of dimensions (ndim): 1
Shape of array: (6,)
Reshaped array (2x3):
 [[1 2 3]
 [4 5 6]]
